#ifndef ERROR_DEFINE_H_INCLUDED
#define ERROR_DEFINE_H_INCLUDED

#define SINGLE_QUOT_ERROR 1
#define DOUBLE_QUOT_ERROR 2
#define UNIDENTIFIED_CHAR 3
#define NOT_EQUAL_ERROR 4
#define NOT_LEGAL_STRING 5
#define NULL_CHAR_ERROR 6

#define TYPE_NOT_MATCH 7
#define	ARRAY_BOUND 8
#define SYNTAX_ERROR 9


#endif // ERROR_DEFINE_H_INCLUDED
